package com.mycompany.app.filereader;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.InvalidPathException;
import java.nio.file.Path;
import java.nio.file.Paths;

/**
 * Reads a txt file generated by the ECharts library to return an SVG as string in Java.
 */
public class TextParser {
    public String parseTextAsString(String filePath) {
        System.out.println("Parsing SVG as string in Java...");

        Path path = null;
        String parsedText = "";

        try {
            path = Paths.get(filePath);
        } catch (InvalidPathException e) {
            System.out.println("Failed to read SVG from ECharts due to invalid path.");
            e.printStackTrace();
        }

        if (path == null) {
            return parsedText;
        }

        try {
            parsedText = Files.readString(path);
        } catch (IOException e) {
            System.out.println("Failed to read svg file generated by ECharts.");
            e.printStackTrace();
        }

        return parsedText;
    }
}
