package edu.hm.hafner.renderer.util;

import org.apache.commons.io.FileUtils;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.io.File;
import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.InvalidPathException;

/**
 * Reads a txt file generated by the ECharts library to return an SVG as string in Java.
 */
public class SvgParser {
    private static final Logger LOG = LoggerFactory.getLogger(SvgParser.class);

    /**
     * Parses the SVG file generated by ECharts as string.
     * @return ECharts SVG as string
     */
    public String parseSvgAsString() {
        LOG.debug("Parsing SVG file content as string in Java...");
        String parsedText = "";

        try {
            final String svgFileName = "echartsSvg.svg";
            final String svgFilePath = Utils.setTempDirectory(svgFileName);

            if (svgFilePath != null && !svgFilePath.isEmpty()) {
                parsedText = FileUtils.readFileToString(new File(svgFilePath), StandardCharsets.UTF_8);
                LOG.info("Successfully parsed SVG string.");
            }
        } catch (InvalidPathException e) {
            LOG.error("Failed to read SVG from ECharts due to invalid file path.", e);
        } catch (IOException e) {
            LOG.error("Failed to read SVG from ECharts due to missing file path.", e);
        }
        return parsedText;
    }
}
