package edu.hm.hafner.renderer.util;

import org.apache.commons.io.FileUtils;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.io.File;
import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.InvalidPathException;

/**
 * Reads a txt file generated by the ECharts library to return an SVG as string in Java.
 */
public class SvgParser {
    private static final Logger LOG = LoggerFactory.getLogger(SvgParser.class);

    private void deleteFile(File svgFile) {
        try {
            FileUtils.delete(svgFile);
        } catch (IOException e) {
            LOG.error("Unable to delete SVG file", e);
        }
    }

    /**
     * Parses the SVG file generated by ECharts as string.
     * @return ECharts SVG as string
     */
    public String parseSvgAsString() {
        String svgAsString = "";

        LOG.debug("Parsing SVG file content as string in Java...");

        try {
            final String svgFileName = "trireme-echarts-output.svg";
            final String svgFilePath = Utils.setTempDirectory(svgFileName);
            final File svgFile = new File(svgFilePath);

            if (!svgFilePath.isEmpty()) {
                svgAsString = FileUtils.readFileToString(svgFile, StandardCharsets.UTF_8);
                deleteFile(svgFile);
            }
        } catch (InvalidPathException | IOException e) {
            LOG.error("Failed to read SVG from ECharts.", e);
        }
        return svgAsString;
    }
}
