name: 'Build and autograde'

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
          check-latest: true
          cache: 'maven'
      - name: Compile, Test and Analysis
        run: mvn -V -ntp clean verify -Dmaven.test.failure.ignore=true
      - name: Autograding
        uses: uhafner/autograding-github-action@v1.7.0
        with:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
          HEAD_SHA: ${{github.event.pull_request.head.sha}}
          CONFIG: >
            {
              "analysis": {
                "maxScore": 100,
                "errorImpact": -5,
                "highImpact": -2,
                "normalImpact": -1,
                "lowImpact": -1
              },
              "tests": {
                "maxScore": 100,
                "passedImpact": 0,
                "failureImpact": -5,
                "skippedImpact": -1
              },
              "coverage": {
                "maxScore": 100,
                "coveredPercentageImpact": 0,
                "missedPercentageImpact": -1
              }
            }
